### ISSUE TITLE
Logo slant?

### ISSUE THREAD

**Issue by cvializ** [cvializ/carlosandlauraswedding.com#1]
Just to try it, not sure if it's too much

```css
/* index.html */
h1.cursive {
  transform: translateX(5px) rotateZ(-5deg);
  transform-origin: center;
}
```
